package steamer;

public class posDic25
{
	String[] data = {
			"ঢং_NN0",
			"ঢঙি_ADJ",
			"ঢং_NN0",
			"ঢক_NN0",
			"ঢক_INT",
			"ঢকঢক_INT",
			"ঢক্কা_NN0",
			"ঢক্কাধ্বনি_NN0",
			"ঢক্কানিনাদ_NN0",
			"ঢন_INT",
			"ঢনঢন_INT",
			"ঢনঢনে_ADJ",
			"ঢপ_NN0",
			"ঢপ_INT",
			"ঢপঢপ_INT",
			"ঢবঢব_INT",
			"ঢল_NN0",
			"ঢলকো_ADJ",
			"ঢলঢল_INT",
			"ঢলঢল_ADJ",
			"ঢলঢলে_ADJ",
			"ঢলতা_NN0",
			"ঢলা_VRB",
			"ঢলাঢলি_NN0",
			"ঢলানে_ADJ",
			"ঢলানি_VRB",
			"ঢলানো_VRB",
			"ঢলেপড়া_VRB",
			"ঢাউস_ADJ",
			"ঢাঁই_NN0",
			"ঢাক_NN0",
			"ঢাকপেটা_VRB",
			"ঢাকবাজানো_VRB",
			"ঢাকেরকাঠিADJdrumstick_ADJNNiNNstigADJtor",
			"ঢাকেরবাঁয়াuselessADJppurteNNADJNNcesorpADJrADJpherNNADJliADJ somethiNNgmerelydecorADJtive",
			"ঢাকেরবাদ্যি drum-beADJt",
			"ঢাকঢাক_NN0",
			"ঢাকঢাক-গুড়গুড়_NN0",
			"ঢাকনা_NN0",
			"ঢাকনি_NN0",
			"ঢাকা_NN0",
			"ঢাকা_VRB",
			"ঢাকা_ADJ",
			"ঢাকাই_ADJ",
			"ঢাকি_NN0",
			"ঢাকিসুদ্ধবিসর্জনtothrowADJwADJyorimmersethedrummerwiththeidol toloseorsADJrcificeeverythiNNg",
			"ঢামালি_NN0",
			"ঢাল_NN0",
			"ঢাল_NN0",
			"ঢালা_VRB",
			"ঢালা_ADJ",
			"ঢালাই_NN0",
			"ঢালা_ADJ",
			"ঢালাইকরা_VRB",
			"ঢালাইকর_NN0",
			"ঢালাই-কারখানা_NN0",
			"ঢালাও_ADJ",
			"ঢালাঢালি_NN0",
			"ঢেলেসাজা_VRB",
			"ঢালী_NN0",
			"ঢালু_ADJ",
			"ঢিঢি_NN0",
			"ঢিঢি_ADJ",
			"ঢিঢিকার_NN0",
			"ঢিঢিক্কার_NN0",
			"ঢিঢিরব_NN0",
			"ঢিপ_INT",
			"ঢিপঢিপ_INT",
			"ঢিপি_NN0",
			"ঢিল_NN0",
			"ঢিলমারা_VRB",
			"ঢিলামি_NN0",
			"ঢিলেমি_NN0",
			"ঢু_NN0",
			"ঢুঁ_NN0",
			"ঢুমারা_VRB",
			"ঢুঁমারা_VRB",
			"ঢুঁড়া_NN0",
			"ঢুঢু_INT",
			"কাজেরবেলায়ঢুঢুfouNNdwADJNNtiNNgwheNNcADJlledupoNNtoproveworth ofNNoworthorvADJlueADJtthetimeofworkorcruciADJltest",
			"ঢুল_NN0",
			"ঢুলঢুলে_ADJ",
			"ঢুলুঢুল_ADJ",
			"ঢুলুঢুলু_ADJ",
			"ঢুলনি ঢুলু",
			"ঢুলুনি ঢুলু",
			"ঢুলা_VRB",
			"ঢুলানো_VRB",
			"ঢুসানো_VRB",
			"ঢুসাঢুসি_NN0",
			"ঢেউ_NN0",
			"ঢেউখেলা_VRB",
			"ঢেউতোলা_VRB",
			"ঢেউ-খেলানো_ADJ",
			"ঢেউ-তোলা_ADJ",
			"ঢেঁকি_NN0",
			"ঢেঁকিকল_NN0",
			"ঢেঁকিশাক_NN0",
			"ঢেঁকিশাল_NN0",
			"ঢেঁকিশালা_NN0",
			"ঢেঁকিস্বর্গেগেলেওধানভানেADJNNexpertworkerhADJstoworkeveNNiNNheADJveNN_ADJdrudgewilldrudgeeveNNiNNheADJveNN",
			"ঢেঁড়স_NN0",
			"ঢেঁড়া_NN0",
			"ঢেঁড়ি_NN0",
			"ঢেঁড়ি_NN0",
			"ঢেঁকুর_NN0",
			"ঢেকুরতোলা_VRB",
			"ঢেপসা_ADJ",
			"ঢেমনা_ADJ",
			"ঢেরা_NN0",
			"ঢেরাসই_NN0",
			"ঢেরি_NN0",
			"ঢেরিকরা_VRB",
			"ঢেলা_NN0",
			"ঢেলামারা_VRB",
			"ঢোঁড়ন_NN0",
			"ঢোঁড়া_NN0",
			"ঢোক_NN0",
			"ঢোকগেলা_VRB",
			"ঢোকা_VRB",
			"ঢুকানো_VRB",
			"ঢোল_NN0",
			"ঢোলপেটা_VRB",
			"ঢোলহওয়া_VRB",
			"নিজেরঢোলনিজেপেটাtobeADJtoNNe'sowNNtrumpet toADVertiseoNNeself",
			"ঢোলক_NN0",
			"ঢোলা_ADJ",
			"ঢোসকা_ADJ",
			"ঢ্যাঙা_ADJ"
			};
	
	public String[] getData()
	{
		return data;
	}
}