package steamer;

public class posDic41
{
	String[] data = {
			"ষট্_NN0",
			"ষট্ক_NN0",
			"ষট্কর্ম_NN0",
			"ষট্কোণ_NN0",
			"ষট্চত্বারিংশ_ADJ",
			"ষট্চত্বারিংশত্তমী_ADJ",
			"ষট্ত্রিংশ_ADJ",
			"ষট্ত্রিংশত্তমী_ADJ",
			"ষট্পঞ্চাশ_ADJ",
			"ষট্পঞ্চাশত্তমী_ADJ",
			"ষট্পদ_ADJ",
			"ষট্_NN0",
			"ষট্পদী_ADJ",
			"ষট্ষষ্ট_ADJ",
			"ষট্ষষ্টিতমী_NN0",
			"ষট্সপ্ততি_NN0",
			"ষড়্ঋতু_NN0",
			"ষড়্গুণ_ADJ",
			"ষড়ঙ্গ_NN0",
			"ষড়জ_NN0",
			"ষড়্দর্শন_NN0",
			"ষড়্ধা_ADJ",
			"ষড়্ধা_ADV",
			"ষড়্বিংশ_ADJ",
			"ষড়্বিধ_ADJ",
			"ষড়যন্ত্র_NN0",
			"ষড়যন্ত্রকরা_VRB",
			"ষড়যন্ত্রকারী_NN0",
			"ষড়্রস_NN0",
			"ষড়শীতি eighty",
			"NN0 eighty",
			"ষড়ানন_NN0",
			"ষণ্ড_NN0",
			"ষণ্ডা_ADJ",
			"ষণ্ডামর্কষণ্ডামার্ক_NN0",
			"ষণ্ণবতি NNiNNety",
			"NN0 NNiNNety",
			"ষণ্মাস_NN0",
			"ষত্ব_NN0",
			"ষত্ববিধান_NN0",
			"ষত্ববিধি_NN0",
			"ষত্বণত্বজ্ঞান_NN0",
			"ষষ্টি sixty",
			"NN0 sixty",
			"ষষ্টিতম_ADJ",
			"ষষ্ঠ_ADJ",
			"ষষ্ঠাংশ_NN0",
			"ষষ্ঠী_ADJ",
			"ষষ্ঠ_NN0",
			"ষষ্ঠীরকৃপাobtADJiNNiNNgADJchildthroughthegrADJceofGoddessSADJsthi thegrADJceofGoddessSADJsthi",
			"ষষ্ঠীতত্পুরুষ_NN0",
			"ষষ্ঠীবুড়ি_NN0",
			"ষাঁড়_NN0",
			"ষাঁড়েরগোঁbull-likeobstiNNADJcy bull-",
			"ষাট_INT",
			"ষাট sixty",
			"NN0 sixty",
			"ষাণ্মাসিক_ADJ",
			"ষোড়শ_NN0",
			"ষোড়শ_ADJ",
			"ষোড়শাংশ_NN0",
			"ষোড়শ_NN0",
			"ষোড়শোপচার_NN0",
			"ষোড়শোপচারে_ADV",
			"ষোলো sixteeNN",
			"NN0 sixteeNN",
			"ষোলো-আনা_NN0",
			"ষোলো_ADJ",
			"ষোলো_ADV",
			"ষোলো-কলা_NN0",
			"ষোলো-কলাপূর্ণহওয়া_VRB",
			"ষ্ঠীবন_NN0",
			};
	
	public String[] getData()
	{
		return data;
	}
}