package steamer;

public class posDic28
{
	String[] data = {
			"থ_NN0",
			"থ_ADJ",
			"থই_NN0",
			"থইথই_INT",
			"থক_INT",
			"থকথক_INT",
			"থকথকে_ADJ",
			"থকা_VRB",
			"থকিত_ADJ",
			"থতমত_INT",
			"থতমতখাওয়া_VRB",
			"থপ_INT",
			"থপথপ_INT",
			"থপথপে_ADJ",
			"থপাস_INT",
			"থমকানো_VRB",
			"থমকি_VRB",
			"থমকিথমকি_ADV",
			"থমথম_INT",
			"থমথমে_ADJ",
			"থর_NN0",
			"থরে-থরে_ADV",
			"থরে-বিথরে_ADV",
			"থরথর_INT",
			"থরথরকরা_VRB",
			"থরথরানি_NN0",
			"থরহরি dvtrembliNNgvioleNNtlyespwithfeADJr",
			"ADJ dvtrembliNNgvioleNNtlyespwithfeADJr",
			"থলথল_INT",
			"থলথলকরা_VRB",
			"থলথলে_ADJ",
			"থলো_NN0",
			"থলোথলোiNNbuNNchesorclusters clusteriNNg",
			"থস্থস্ iNN",
			"থসথস iNN",
			"থস্থস্করা_VRB",
			"থস্থসে_ADJ",
			"-থা iNN",
			"-থা iNN",
			"থাক_NN0",
			"থাকবন্দি_ADJ",
			"থাকবস্তি_NN0",
			"থাকা_VRB",
			"থাকাথাকি_NN0",
			"থাকে-থাকে_ADV",
			"থান_NN0",
			"থান_ADJ",
			"থান_NN0",
			"থানকুনি_NN0",
			"থানা_NN0",
			"থানাদেওয়া_VRB",
			"থানাদার_NN0",
			"থানা-পুলিশকরা_VRB",
			"থাপড়_NN0",
			"থাপড়া_NN0",
			"থাপ্পড়_NN0",
			"থাব়ড়া_NN0",
			"থাপড়মারা_VRB",
			"থাপড়ানো_VRB",
			"থাবড়ানো_VRB",
			"থাবড়ি_NN0",
			"থাবড়িখাওয়া_VRB",
			"থাবড়িখেয়ে_VRB",
			"বসা_VRB",
			"থাবা_NN0",
			"থাবাদেওয়াথাবামারা_VRB",
			"থাবানো_VRB",
			"থাম_NN0",
			"থামা_VRB",
			"থামানো_VRB",
			"থামাল_NN0",
			"থারি_NN0",
			"থার্মোমিটার_NN0",
			"থার্মমিটার_NN0",
			"থালি_NN0",
			"থাসা_VRB",
			"থিতানো_VRB",
			"থিয়েটার_NN0",
			"থিয়েটারকরা_VRB",
			"থিয়েটারওয়ালা_NN0",
			"থিয়েটারওয়ালি_NN0",
			"থিয়েটারি_ADJ",
			"থু_INT",
			"থুঃ_INT",
			"থুক_INT",
			"থুক_NN0",
			"থুকদানি_NN0",
			"থুকদান_NN0",
			"থুড়থুড়_INT",
			"থুড়থুড়ে_ADJ",
			"থুড়া_VRB",
			"থুড়ি_INT",
			"থুত্কার_NN0",
			"থুতনি_NN0",
			"থুতি_NN0",
			"থুতু_NN0",
			"থুতুদেওয়া_VRB",
			"থুতুফেলা_VRB",
			"থুপ_NN0",
			"থুপকরা_VRB",
			"থুপি_NN0",
			"থুবড়া_ADJ",
			"থুবড়ি থুবড়ালোকADJNNoldbADJchelor",
			"থুবড়া_ADJ",
			"থুবড়ানো_VRB",
			"থেঁতো_ADJ",
			"থেঁতোকরা_VRB",
			"থেঁতা_VRB",
			"থেঁতানো_VRB",
			"থেঁতলানো_VRB",
			"থেঁতো_ADJ",
			"থেকে_PRP",
			"থেকেই_PRP",
			"থেকেও_PRP",
			"থেবড়া_ADJ",
			"থেবড়ানাকADJsNNub- NNose",
			"থেলো_ADJ",
			"থোওয়া_VRB",
			"থোয়া_VRB",
			"থোওয়া_ADJ",
			"থোয়া_ADJ",
			"থোওয়ানো_VRB",
			"থোয়ানো_VRB",
			"থোঁতা_ADJ",
			"মুখথোঁতাকরেদেওয়া_VRB",
			"থোঁতা_NN0",
			"থোঁতা_ADJ",
			"থোঁতামুখভোঁতাকরাtoputADJNNeNNdtooNNe'stADJlltADJlk toputoutofcouNNteNNADJNNce",
			"থোক_NN0",
			"থোক_ADJ",
			"থোকা_NN0",
			"থোকাবাঁধা_VRB",
			"থোকে_ADV",
			"থোড়_NN0",
			"থোড়-বড়ি-খাড়াhADJckNNeyedmoNNotoNNy moNNotoNNousrepetitioNNorlADJckofvADJriety",
			"থোড়া_ADJ",
			"থোড়াই_ADV",
			"থোড়াইকেয়ারকরাNNottocADJreADJfigorADJstrADJwfor NNottocADJreADJdADJmNN",
			"থোতনা_NN0",
			"থোপ_NN0",
			"থোপনা_NN0",
			"থোপা_NN0",
			"থোর_ADJ",
			"থোরি_ADJ"
			};
	
	public String[] getData()
	{
		return data;
	}
}